import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '📘 Introducción',
      items: [
        'introduction/bienvenida',
        'introduction/caracteristicas-principales',
        'introduction/casos-de-uso',
        'introduction/requisitos-previos',
      ],
    },
    {
      type: 'category',
      label: '🚀 Guía de Inicio',
      items: [
        'guia-inicio/instalacion',
        'guia-inicio/configuracion-inicial',
      ],
    },
    {
      type: 'category',
      label: '🏗️ Arquitectura',
      items: [
        'arquitectura/vista-general',
        'arquitectura/stack-tecnologico',
        'arquitectura/estructura-del-proyecto',
      ],
    },
    {
      type: 'category',
      label: '🔗 Inventario de Recursos',
      items: [
        {
          type: 'category',
          label: 'Ambientes',
          items: [
            'inventario/ambientes/desarrollo',
            'inventario/ambientes/staging',
            'inventario/ambientes/produccion',
          ],
        },
        {
          type: 'category',
          label: 'Servicios Externos',
          items: [
            'inventario/servicios-externos/base-de-datos',
            'inventario/servicios-externos/apis-integradas',
            'inventario/servicios-externos/servicios-cloud',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '📋 Guías de Uso',
      items: [
        'guias/gestion-de-usuarios',
        'guias/gestion-de-campanas',
        'guias/gestion-de-clientes',
        'guias/operaciones-comunes',
      ],
    },
    {
      type: 'category',
      label: '🔌 API Reference',
      items: [
        'api/introduccion-api',
        'api/autenticacion',
        'api/endpoints',
        'api/ejemplos-de-uso',
        'api/codigos-de-error',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Configuración',
      items: [
        'configuracion/variables-de-entorno',
        'configuracion/configuracion-de-servicios',
        'configuracion/integraciones-externas',
      ],
    },
    {
      type: 'category',
      label: '🗄️ Base de Datos',
      items: ['base-de-datos/esquema'],
    },
    {
      type: 'category',
      label: '🔐 Seguridad',
      items: [
        'seguridad/mejores-practicas',
        'seguridad/autenticacion-autorizacion',
      ],
    },
    {
      type: 'category',
      label: '🚢 Despliegue',
      items: [
        'despliegue/ambientes',
        'despliegue/pipeline-ci-cd',
        'despliegue/docker',
        'despliegue/configuracion-de-servidores',
        'despliegue/monitoreo-alertas',
      ],
    },
    {
      type: 'category',
      label: '❓ FAQ',
      items: ['faq/preguntas-frecuentes'],
    },
    {
      type: 'category',
      label: '📝 Changelog',
      items: ['changelog/version-actual'],
    },
    {
      type: 'category',
      label: '📞 Soporte',
      items: ['soporte/involucrados', 'soporte/reportar-bug'],
    },
    // Move existing tutorial folders to the end to honor the request
    {type: 'autogenerated', dirName: 'tutorial-basics'},
    {type: 'autogenerated', dirName: 'tutorial-extras'},
  ],
};

export default sidebars;
